### ISSUE TITLE
Persist Database type ASE not supported

### ISSUE THREAD

**Issue by aseiseasy** [goranschwarz/DbxTune#1]
H2 seems the only available recording database repository that works, although "-T ASE|ASA" options are documented.   The DDL created for recording database is not compatible with ASE as several datatypes like "numeric(40,1)" , "varchar(64k)" , and primary key definitions that include null columns, are attempted to be created.  

I'd dearly like to query my recordings separately from asetune.   Will there ever be support for recording repositories other than h2?

**Comment by goranschwarz** [comment]
PCS (Persistence Counter Store) for other databases than H2
* I still have the “idea” to use a PCS other than H2... But for the moment H2 is the supported option!

Hopefully in the latest “unofficial” development drop (which you can find here: https://gorans.org/www/asetune/tmp/asetune_2022-10-14.zip)
It might work a *little* better... (I generate table DDL in a slightly better way)... but I normally only test it on H2!
BTW: Yes I will have to make a new official release *very* soon, current official version will stop working at the end of the month!

To Query a PCS (recording) , that is done in H2 
* I do that all the time
* I simply use the tool “SQL Window” (sqlw.bat) which is part of the DbxTune package!
(or you can use any other tool like DBeaver... and other tools that can connect using a JDBC Driver)

Here is how you do it: (see picture at the end)
* Start SQL Window (goto _DbxTuneInstallDir_/bin and start sqlw.bat)
* Press “Connect”
* Choose tab “JDBC” or “Load Recorded Session”, and fill in:
  * JDBC Driver: org.h2.Driver
  * JDBC Url: jdbc:h2:file:C:\Users\goran\.dbxtune\data\PROD_A1_ASE_2022-11-02;IFEXISTS=TRUE
  * Username: sa                            _(or specify the username you choose when starting the recording)_
  * Password: _--leave-it-blank--   (or specify the password you choose when starting the recording)_
* Write your query and execute
* TIP: Use ctrl+space to get a list of table names

In fact I use SQL Window to connect to “any” DBMS to execute SQL Statements (if you use Sybase Replication Server, it will also work there)
* Have you tested to use “SQL Windows” for SAP/Sybase ASE

Here is a picture of how I’m doing it!
![image](https://user-images.githubusercontent.com/4483245/199754104-e01e3cb3-ddef-4ee9-b41f-f4326cb40a92.png)

Hope this helped... If not, please let me know!
/Goran Schwarz

**Comment by aseiseasy** [comment]
No, i'm not talking about casually opening a window, and typing this or
that SQL like i'm browsing data, I'm looking to use the repository data
from the linux command line, much like "isql".  I suppose there might be
something out there that does this.  A "jisql" if you will.

I collect (--nogui) data on linux server(s).  Needing an X-window, or
shipping files to a PC to use SQL Window isn't in the cards.  Even if I
wanted to, I assume  there is an "h2" url format that could get me to my
linux h2 database file.

So,... why is "-T ASE|ASA" in the readme/code?  I'm just assuming you are
essentially saying that ASE|ASA is not really supported as a persist DB
quite yet.  which is fine.

Thanks -

**Comment by goranschwarz** [comment]
OK, what is the problem you are trying to solve (with: _get data via a cmd line tool (like isql)_), is it:
* Creating your own graphs/charts?
* Detecting "stuff" in the recording and generate/send alarms to some other system?
* Digging out information from a recording, which may be used to create a "Daily Summary Report" or similar

## Here is How I do it:
I'm running DbxTune at several of my customers (which I do consultancy work for)
And of course I'm using NO-GUI mode to collect data from (mostly: Sybase ASE, Sybase RepServer, MS SQL Server and Postgres)
I Configure the collectors (for example AseTune) to:
* Send Alarms when various thresholds are crossed
* Sending Daily Summary reports (so I can see what has happened during a day), normally sent to "someone" by mail
* Collectors are also sending "trend graph" information to a Central server "DbxCentral" (see below: trend graphs at DbxCentral is stored for 14 months by default)
* Note: A detailed database recording (for every collector instance) is a recording "per day" instanceName_YYYY-MM-DD, which is deleted when disk space starts to get low

In DbxCentral (which is a Web interface) you can:
* View trend graphs for each Collector Instance
* _drill down_ on specific Graphs/Chart to view a longer period (maybe a month or the whole year to se long trends, or abrupt changes within the period)
* Active alarms are displayed 
* You can view older Daily Summary Reports (_once again to compare and establish trends, that may not be available in the trend graphs_)
* View what detailed database recordings are available (the ones recorded from AseTune or some other collector)
  * You can click on a old detailed recording, and if you have AseTune GUI running on your workstation (PC/Mac) it will connect to the recorded database (which resides on Linux), and you can view the recorded information from the XxxTune GUI)
* And a bunch of other stuff...
* Some of my customers create there own "profiles" (there own set of charts for various servers), and has that as a "dashboard" on there monitoring screens/tv's

## Example of DbxCentral
You can see an example of the DbxCentral here: http://gorans.org:8080/
The above link is my home test environment running: 4 different versions of ASE, some SQL Servers, Postgres and MySQL ...
The system is **idling** most of the time... so you wont see any interesting workload, but you get the idea :)
NOTE: Please be a bit gentle when you are on the system...

## Summary
So I'm trying to figure out what you are trying to accomplish?
* If it's a setup like "DbxCentral"???    --- I can help you configure that :)
* If it's "something else", let me know what it is... 
  If it's of interesting for "others" (general purpose), let create what you need, so "everybody" can use it :)

Please let me know
/Goran

**Comment by goranschwarz** [comment]
@aseiseasy Did you have any questions on the above, or should I close the issue?

**Comment by goranschwarz** [comment]
No feedback from requestor
